const FETCH_PROMO_GROUP = "FETCH_PROMO_GROUP";
const FETCH_PROMO_GROUP_SUCCESS = "FETCH_PROMO_GROUP_SUCCESS";
const FETCH_PROMO_GROUP_FAILURE = "FETCH_PROMO_GROUP_FAILURE";
const UPDATE_SELECTED_PROMO_GROUP = "UPDATE_SELECTED_PROMO_GROUP";
const UPDATE_SELECTED_ALL_PROMO_GROUP = "UPDATE_SELECTED_ALL_PROMO_GROUP";

export default {
  FETCH_PROMO_GROUP,
  FETCH_PROMO_GROUP_SUCCESS,
  FETCH_PROMO_GROUP_FAILURE,
  UPDATE_SELECTED_PROMO_GROUP,
  UPDATE_SELECTED_ALL_PROMO_GROUP
};
