const FETCH_HISTORY_TRANSACTION = "FETCH_HISTORY_TRANSACTION";
const FETCH_HISTORY_TRANSACTION_SUCCESS = "FETCH_HISTORY_TRANSACTION_SUCCESS";
const FETCH_HISTORY_TRANSACTION_FAILURE = "FETCH_HISTORY_TRANSACTION_FAILURE";

export default {
  FETCH_HISTORY_TRANSACTION,
  FETCH_HISTORY_TRANSACTION_SUCCESS,
  FETCH_HISTORY_TRANSACTION_FAILURE
};
