const FETCH_USER = "FETCH_USER";
const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export default {
  FETCH_USER,
  FETCH_USER_SUCCESS,
  FETCH_USER_FAILURE
};
