const FETCH_SUPPLIER = "FETCH_SUPPLIER";
const FETCH_SUPPLIER_SUCCESS = "FETCH_SUPPLIER_SUCCESS";
const FETCH_SUPPLIER_FAILURE = "FETCH_SUPPLIER_FAILURE";

export default {
    FETCH_SUPPLIER,
    FETCH_SUPPLIER_SUCCESS,
    FETCH_SUPPLIER_FAILURE
}