const FETCH_PROMO_USER = "FETCH_PROMO_USER";
const FETCH_PROMO_USER_SUCCESS = "FETCH_PROMO_USER_SUCCESS";
const FETCH_PROMO_USER_FAILURE = "FETCH_PROMO_USER_FAILURE";
const UPDATE_SELECTED_PROMO_USER = "UPDATE_SELECTED_PROMO_USER";
const UPDATE_SELECTED_ALL_PROMO_USER = "UPDATE_SELECTED_ALL_PROMO_USER";

export default {
  FETCH_PROMO_USER,
  FETCH_PROMO_USER_SUCCESS,
  FETCH_PROMO_USER_FAILURE,
  UPDATE_SELECTED_PROMO_USER,
  UPDATE_SELECTED_ALL_PROMO_USER
};
